# NUMPY : Package for Multidimensional Array

### Vector(1D) and Matrix(2D or 1D)

In [39]:
import numpy as np

In [40]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [41]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [42]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(5,30)   # print all the numbers from given range to n-1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
np.arange(5,30,5) # print number from given range to n-1 in diff of 5(last parameter is for the diff b/w two number)

array([ 5, 10, 15, 20, 25])

In [45]:
np.zeros(100)  #array of zeros (100 times 0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros(10,dtype=int)   #integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.ones((2,5))    #array of ones 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.linspace(0,1,5) #linear spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [51]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [52]:
np.random.rand(2,4)     #random numbers

array([[0.1692689 , 0.82143321, 0.56753357, 0.00403429],
       [0.18071566, 0.99210205, 0.42599536, 0.68818428]])

In [53]:
np.random.randn(2,4)

array([[ 1.43668112,  1.4880087 , -0.80228578,  0.39897309],
       [ 0.52629702,  0.92423978, -0.66691925, -0.32187905]])

In [56]:
np.random.randint(2,10)    #will generate any random number between 2 and 10

2

In [57]:
np.random.randint(20,56,100)  #generate 100 random number b/w 20 to 56,duplicates are also possible

array([54, 24, 40, 23, 22, 46, 36, 55, 25, 30, 44, 26, 47, 46, 51, 20, 29,
       55, 20, 25, 20, 34, 32, 31, 39, 35, 20, 46, 32, 38, 29, 42, 40, 26,
       26, 33, 26, 51, 52, 31, 49, 39, 38, 42, 31, 47, 53, 33, 52, 20, 50,
       45, 41, 35, 22, 49, 24, 23, 29, 38, 38, 51, 28, 31, 51, 22, 51, 49,
       23, 43, 51, 42, 24, 33, 50, 54, 27, 55, 24, 24, 41, 25, 54, 26, 26,
       55, 22, 22, 44, 25, 20, 25, 40, 52, 34, 43, 28, 38, 38, 53])

In [58]:
sample_array=np.arange(30)   #generate an array from 0 to n-1
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
rand_array=np.random.randint(0,100,20) #generate 20 random number b/w 0 to 100
rand_array

array([49, 51, 42,  0, 20, 27, 54, 82, 55, 87, 60, 38,  6, 94, 49, 75, 80,
       55, 30,  3])

In [61]:
sample_array.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [62]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [63]:
sample_array.reshape(3,11)  #equal division is not possible

ValueError: cannot reshape array of size 30 into shape (3,11)

In [64]:
rand_array.min()  #minimum value

0

In [65]:
rand_array.argmin()   #index of minimum value

3

In [66]:
rand_array.max()

94

In [67]:
rand_array.argmax()  #index of maximum value

13

In [68]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
sample_array.shape

(30,)

In [70]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
sample_array.dtype

dtype('int32')

In [72]:
import numpy as np

In [74]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
a=np.random.rand(2,3)
a

array([[0.20938011, 0.03511122, 0.33505888],
       [0.06397021, 0.34797093, 0.4473981 ]])

In [77]:
import numpy as np

In [78]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [79]:
sample_array[8]

18

In [80]:
sample_array[2:5]

array([12, 13, 14])

In [81]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [82]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
sample_array[0:7]


array([10, 11, 12, 13, 14, 15, 16])

In [84]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [85]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two - Dimensional array

In [87]:
import numpy as np

In [88]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [89]:
sample_matrix[0][2]

1

In [90]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [91]:
sample_matrix[2]

array([56, 76, 24,  7])

# Custom indexing

In [92]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [93]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

# Selection Techniques

In [94]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [95]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [96]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [98]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [99]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [100]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [101]:
np.max(sample_array)

30

In [102]:
np.min(sample_array)

1

In [103]:
np.argmax(sample_array)

29

In [104]:
np.argmin(sample_array)

0

In [105]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [106]:
np.std(sample_array)

8.65544144839919

In [107]:
np.var(sample_array)

74.91666666666667

In [108]:
np.mean(sample_array)

15.5

In [109]:
array=np.random.randn(3,6)
array

array([[-0.3256611 ,  0.72607079,  0.13051455,  1.58383417, -1.24391578,
         0.04216565],
       [-0.99674177,  0.60109893,  0.87960809, -0.37843174,  0.25194386,
         0.19920306],
       [-0.90500159, -0.72081276, -0.26877029, -0.25436619,  0.42171517,
        -0.55788128]])

In [110]:
np.round(array,decimals=2)

array([[-0.33,  0.73,  0.13,  1.58, -1.24,  0.04],
       [-1.  ,  0.6 ,  0.88, -0.38,  0.25,  0.2 ],
       [-0.91, -0.72, -0.27, -0.25,  0.42, -0.56]])

In [111]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [112]:
import pandas as pd
import numpy as np

In [113]:
labels=['w','x','y','z']
sample_list=[10,20,30,40]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

In [114]:
pd.Series(data=sample_list)

0    10
1    20
2    30
3    40
dtype: int64

In [115]:
pd.Series(data=sample_list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [116]:
pd.Series(array,labels)

w    1
x    2
y    3
z    4
dtype: int32

In [117]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

# Pandas dataframe and indexing

In [118]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [119]:
sports1['football']

2

In [120]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [121]:
sports1+sports2   #NaN because baseball & basketball both are present in only single sports

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [122]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5 '.split())
df1

Score1    Score2    Score3    Score4    Score5
A -1.222640 -0.744032  0.650664 -1.398022  0.724224
B  0.763697 -0.247066  1.579075 -0.714420  1.408670
C -1.372651 -0.957534  0.387931  1.099684  0.774936
D  0.818773 -2.859851  1.196219  2.245899  1.610711
E  0.160740 -2.742904  0.847622 -1.049850 -0.094697
F -0.215021 -0.949196 -1.002181 -0.914834  1.280626
G -0.132617 -2.303355  1.055668  0.402754 -1.599261
H -0.021003  1.315607 -0.725552  0.432360 -0.323005

In [123]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A -1.222640 -0.744032  0.650664 -1.398022  0.724224 -1.966672
B  0.763697 -0.247066  1.579075 -0.714420  1.408670  0.516631
C -1.372651 -0.957534  0.387931  1.099684  0.774936 -2.330185
D  0.818773 -2.859851  1.196219  2.245899  1.610711 -2.041079
E  0.160740 -2.742904  0.847622 -1.049850 -0.094697 -2.582164
F -0.215021 -0.949196 -1.002181 -0.914834  1.280626 -1.164217
G -0.132617 -2.303355  1.055668  0.402754 -1.599261 -2.435972
H -0.021003  1.315607 -0.725552  0.432360 -0.323005  1.294604

In [125]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123